services:
  postgres:
    image: "postgres:16-alpine"
    restart: "always"
    environment:
      - "POSTGRES_USER=$DATABASE_USERNAME"
      - "POSTGRES_PASSWORD=$DATABASE_PASSWORD"
      - "POSTGRES_DB=$DATABASE_NAME"
    ports:
      - "$DATABASE_PORT:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"

  minio:
    image: minio/minio
    restart: always
    command: server --console-address ":$MINIO_CONSOLE_PORT" /data
    environment:
      - MINIO_ROOT_USER=$MINIO_USERNAME
      - MINIO_ROOT_PASSWORD=$MINIO_PASSWORD
      - MINIO_DEFAULT_BUCKET=$S3_BUCKET_NAME
    ports:
      - "$MINIO_PORT:9000"
      - "$MINIO_CONSOLE_PORT:9001"
    volumes:
      - "./data/minio:/data"
