packages:
  - "packages/*"
  - "apps/*"
  - "tooling/*"

catalog:
  typescript: 5.3.3
  eslint: 9.6.0

catalogs:
  nextjs:
    react-dom: 18.3.1
    react: 18.3.1
    "@types/react": 18.3.3
    "@types/node": 20.14.10
    "@types/react-dom": 18.3.0
