import type { Metadata } from "next"
import { ReactNode } from "react"
import { Toaster } from "react-hot-toast"

import Providers from "@/app/providers"

import "./globals.css"

type Props = {
  children: ReactNode
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}
const RootLayout = (props: Props) => {
  const { children } = props

  return (
    <html lang="en">
      <body>
        <Toaster
          toastOptions={{
            className: "toast",
          }}
        />
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}

export default RootLayout
