name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 9.5.0

    - uses: actions/setup-node@v4
      with:
        node-version: 20.9.0
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm install
