name: CI

on:
  pull_request:
  push:
    branches: ["main", "config/**"]
  merge_group:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/setup

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Format
        run: pnpm run format

      - name: Typecheck
        run: pnpm run typecheck

      - name: Check expo
        run: pnpm run mobile:check
