name: CI

on:
  pull_request:
  push:
    branches: ["main", "config/**"]
  merge_group:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint && bun run --filter='**' lint

      - name: Format
        run: bun run format

      - name: Typecheck
        run: bun run typecheck

      - name: Check expo
        run: bun run mobile:check
