name: CI

on:
  pull_request:
  push:
    branches: ["main", "config/**"]
  merge_group:

jobs:
  check:
    runs-on: upnpmtu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.4.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Format
        run: pnpm run format

      - name: Typecheck
        run: pnpm run typecheck

      - name: Check expo
        run: pnpm run mobile:check
