name: CI

on:
  pull_request:
  push:
    branches: ["main", "config/**"]
  merge_group:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm ci

      - name: Lint
        run: npm run lint && npm run lint -ws --if-present

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm ci

      - name: Format
        run: npm run format

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

  expo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm ci

      - name: Check expo
        run: npm run mobile:check
